# Generated by Django 2.1.7 on 2019-02-24 00:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 24, 0, 7, 58, 885767), verbose_name='date published'),
        ),
    ]
